
[env]
MISE_EXPERIMENTAL = "1"
STARSHIP_CONFIG = "{{config_root}}/.starship.toml"
_.path = ["bin"]

[hooks]
enter = """
[ -x "$(command -v toilet)" ] && toilet --gay -f term -F border ssfa-tools
[ -x "$(command -v features)" ] && features githook -q
"""
