name: CI

on:
  push:
    branches: ["**"]
  pull_request:

defaults:
  run:
    working-directory: features

jobs:
  test:
    name: RSpec
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4"
          bundler-cache: true
          working-directory: features

      - name: Run RSpec
        run: bundle exec rspec

  build:
    name: Gem Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4"
          bundler-cache: true
          working-directory: features

      - name: Build gem
        run: bundle exec rake build
