# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in features.gemspec
gemspec

gem "irb"
gem "rake", "~> 13.0"

gem "rubocop", "~> 1.21"

group :test do
  gem "rspec", "~> 3.0"
  gem "simplecov", require: false
end

